Review 1
Melk0/stellar-burgers pull request #1
Opened 2024-09-26 21:32 UTC by Melk0

2024-09-26 22:03 UTC, SergeyK2004 requested changes
Здравствуйте. 

Работа проделана огромная

Что сделано отлично:
Отлично сделана логика проверки, был ли пользователь на сайте, и показывать ли страницу с деталями, а не модально окно. Здорово, что выделяется активная страница в главном меню. Бургер корректно собирается с возможностью менять ингредиенты местами.

Что нужно исправить:

* https://disk.yandex.ru/d/TK7eEgCYTbvU8g Выполненный заказ невозможно открыть
* Нужно центрировать контент на странице с деталями ингредиента, скрин https://disk.yandex.ru/d/6YehwC6cUigzoA
* Не работает кнопка "Обновить" в Ленте заказов

Исправьте, пожалуйста, недочеты и работа будет принята. Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 
Напоминаю, что работа может быть принята только после исправления всех критических замечаний Нужно исправить.

Удачного рефакторинга кода.

2024-09-26 22:03 UTC, SergeyK2004 commented on src/components/app/app.tsx
> +  const bgLocation = location.state?.background;
Отлично:
Отлично сделана проверка открывать модальное окно или отдельную страницу.

2024-09-26 22:03 UTC, SergeyK2004 commented on src/components/burger-ingredient/burger-ingredient.tsx
> +import { useDispatch } from '../../services/store';
Отлично:
Правильно, что используете типизированные хуки

2024-09-26 22:03 UTC, SergeyK2004 commented on src/components/ui/app-header/app-header.tsx
> +          <NavLink
Отлично:
Использование NavLink в главном меню

2024-09-26 22:03 UTC, SergeyK2004 commented on src/services/burgerConstructorSlice.ts
> +        const id = uuidv4();
Отлично:
Здорово что вынесли создание id в prepare

2024-09-27 19:03 UTC, Melk0 reviewed
Review 2

2024-09-27 20:06 UTC, SergeyK2004 requested changes
Очень хорошо. 
Почти все недочеты устранены. Заказ теперь открывается, но его форма отличается от приведенной у вас в макете:

* https://disk.yandex.ru/d/tCyF5RUuPQfS4A Форма заказа не соответствует макету
* https://disk.yandex.ru/d/t8DNZJa4zxQe6g При выводе в отдельной странице форма заказа не корректна

Исправьте отображение заказа и можно принимать работу.

2024-09-28 04:10 UTC, SergeyK2004 approved these changes
Отличная работа
Вы молодец.
Ваша работа принята. Желаю успехов в дальнейшем обучении.
Обратите внимание, что сейчас вам нужно смержить ветку review в main и после этого, при выполнении проектной работы следующего спринта создать новую ветку review, в которой вы будете покрывать приложение тестами. Старую ветку review можно удалить.

Можно лучше: 
https://skr.sh/sRweQt03B6G При открытии заказа, пока происходит загрузка данных, отображается некорректный заголовок модального окна. Будет здорово, если на время загрузки будет отбрадаться корректное окно.

2024-09-29 09:00 UTC, merged